
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    config:
      materialized: ephemeral
    columns:
      - name: product_id
        description: "The primary key for this table"


  - name: my_second_dbt_model
    description: "A starter dbt model"
    config:
      materialized: ephemeral
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
